<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <FingerprintAssets>false</FingerprintAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.4" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DungeonGame.Engine\DungeonGame.Engine\DungeonGame.Engine.csproj" />
  </ItemGroup>

  <Target Name="BuildVite" AfterTargets="Build">
    <PropertyGroup>
      <VitePublicFramework>..\DungeonGame.UI\public\_framework\</VitePublicFramework>
    </PropertyGroup>

    <RemoveDir Directories="$(VitePublicFramework)" />

    <ItemGroup>
      <WasmFiles Include="$(TargetDir)wwwroot\_framework\**\*.*" />
    </ItemGroup>

    <Copy
      SourceFiles="@(WasmFiles)"
      DestinationFolder="$(VitePublicFramework)%(RecursiveDir)"
      SkipUnchangedFiles="false" />
  </Target>

</Project>
